<?php

namespace Proxy\__CG__\Administrativo;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Acao extends \Administrativo\Acao implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getNome()
    {
        $this->__load();
        return parent::getNome();
    }

    public function getControle()
    {
        $this->__load();
        return parent::getControle();
    }

    public function getIdentidade()
    {
        $this->__load();
        return parent::getIdentidade();
    }

    public function setControle(\Administrativo\Controle $controle)
    {
        $this->__load();
        return parent::setControle($controle);
    }

    public function setNome($nome)
    {
        $this->__load();
        return parent::setNome($nome);
    }

    public function getUsuarioAcoes()
    {
        $this->__load();
        return parent::getUsuarioAcoes();
    }

    public function addAcao(\Administrativo\Acao $acao)
    {
        $this->__load();
        return parent::addAcao($acao);
    }

    public function getAcaoAcl()
    {
        $this->__load();
        return parent::getAcaoAcl();
    }

    public function setAcaoAcl($sAcaoAcl)
    {
        $this->__load();
        return parent::setAcaoAcl($sAcaoAcl);
    }

    public function getSubAcoes()
    {
        $this->__load();
        return parent::getSubAcoes();
    }

    public function setSubAcoes($sSubAcoes)
    {
        $this->__load();
        return parent::setSubAcoes($sSubAcoes);
    }

    public function getGeradorDados()
    {
        $this->__load();
        return parent::getGeradorDados();
    }

    public function setGeradorDados($lGeradorDados)
    {
        $this->__load();
        return parent::setGeradorDados($lGeradorDados);
    }

    public function getUsuarioContribuinteAcoes()
    {
        $this->__load();
        return parent::getUsuarioContribuinteAcoes();
    }

    public function addUsuarioContribuinteAcoes(\Administrativo\UsuarioContribuinteAcao $usuario_contribuinte_acoes)
    {
        $this->__load();
        return parent::addUsuarioContribuinteAcoes($usuario_contribuinte_acoes);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'acao', 'identidade', 'acaoacl', 'sub_acoes', 'gerador_dados', 'controle', 'usuario_acoes', 'usuario_contribuinte_acoes');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}