<?php

namespace Proxy\__CG__\Administrativo;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Usuario extends \Administrativo\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setLogin($l)
    {
        $this->__load();
        return parent::setLogin($l);
    }

    public function getLogin()
    {
        $this->__load();
        return parent::getLogin();
    }

    public function setSenha($s)
    {
        $this->__load();
        return parent::setSenha($s);
    }

    public function getSenha()
    {
        $this->__load();
        return parent::getSenha();
    }

    public function getNome()
    {
        $this->__load();
        return parent::getNome();
    }

    public function setNome($nome)
    {
        $this->__load();
        return parent::setNome($nome);
    }

    public function getTelefone()
    {
        $this->__load();
        return parent::getTelefone();
    }

    public function setTelefone($telefone)
    {
        $this->__load();
        return parent::setTelefone($telefone);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getHabilitado()
    {
        $this->__load();
        return parent::getHabilitado();
    }

    public function setHabilitado($habilitado)
    {
        $this->__load();
        return parent::setHabilitado($habilitado);
    }

    public function getAdministrativo()
    {
        $this->__load();
        return parent::getAdministrativo();
    }

    public function setAdministrativo($administrativo)
    {
        $this->__load();
        return parent::setAdministrativo($administrativo);
    }

    public function getUsuariosContribuintes()
    {
        $this->__load();
        return parent::getUsuariosContribuintes();
    }

    public function addUsuariosContribuintes(\Administrativo\UsuarioContribuinte $uc)
    {
        $this->__load();
        return parent::addUsuariosContribuintes($uc);
    }

    public function getAcoes()
    {
        $this->__load();
        return parent::getAcoes();
    }

    public function addAcao(\Administrativo\Acao $acao)
    {
        $this->__load();
        return parent::addAcao($acao);
    }

    public function delAcao(\Administrativo\Acao $acao)
    {
        $this->__load();
        return parent::delAcao($acao);
    }

    public function getPerfil()
    {
        $this->__load();
        return parent::getPerfil();
    }

    public function setPerfil(\Administrativo\Perfil $perfil)
    {
        $this->__load();
        return parent::setPerfil($perfil);
    }

    public function getTipo()
    {
        $this->__load();
        return parent::getTipo();
    }

    public function setTipo($tipo)
    {
        $this->__load();
        return parent::setTipo($tipo);
    }

    public function getCgm()
    {
        $this->__load();
        return parent::getCgm();
    }

    public function setCgm($cgm)
    {
        $this->__load();
        return parent::setCgm($cgm);
    }

    public function getUsuarios_acoes()
    {
        $this->__load();
        return parent::getUsuarios_acoes();
    }

    public function setUsuarios_acoes(\Doctrine\Common\Collections\ArrayCollection $usuarios_acoes)
    {
        $this->__load();
        return parent::setUsuarios_acoes($usuarios_acoes);
    }

    public function getCnpj()
    {
        $this->__load();
        return parent::getCnpj();
    }

    public function setCnpj($cnpj)
    {
        $this->__load();
        return parent::setCnpj($cnpj);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'login', 'senha', 'nome', 'fone', 'email', 'habilitado', 'administrativo', 'tipo', 'cgm', 'cnpj', 'usuarios_contribuintes', 'usuarios_acoes', 'acoes', 'perfil');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}