<?php

namespace Proxy\__CG__\Contribuinte;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Nota extends \Contribuinte\Nota implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getNota()
    {
        $this->__load();
        return parent::getNota();
    }

    public function setNota($nota)
    {
        $this->__load();
        return parent::setNota($nota);
    }

    public function getDt_nota()
    {
        $this->__load();
        return parent::getDt_nota();
    }

    public function setDt_nota($dt_nota)
    {
        $this->__load();
        return parent::setDt_nota($dt_nota);
    }

    public function getHr_nota()
    {
        $this->__load();
        return parent::getHr_nota();
    }

    public function setHr_nota($hr_nota)
    {
        $this->__load();
        return parent::setHr_nota($hr_nota);
    }

    public function getCod_verificacao()
    {
        $this->__load();
        return parent::getCod_verificacao();
    }

    public function setCod_verificacao($cod_verificacao)
    {
        $this->__load();
        return parent::setCod_verificacao($cod_verificacao);
    }

    public function getS_dados_discriminacao()
    {
        $this->__load();
        return parent::getS_dados_discriminacao();
    }

    public function setS_dados_discriminacao($s_dados_discriminacao)
    {
        $this->__load();
        return parent::setS_dados_discriminacao($s_dados_discriminacao);
    }

    public function getS_vl_servicos()
    {
        $this->__load();
        return parent::getS_vl_servicos();
    }

    public function setS_vl_servicos($s_vl_servicos)
    {
        $this->__load();
        return parent::setS_vl_servicos($s_vl_servicos);
    }

    public function getS_vl_deducoes()
    {
        $this->__load();
        return parent::getS_vl_deducoes();
    }

    public function setS_vl_deducoes($s_vl_deducoes)
    {
        $this->__load();
        return parent::setS_vl_deducoes($s_vl_deducoes);
    }

    public function getS_vl_bc()
    {
        $this->__load();
        return parent::getS_vl_bc();
    }

    public function setS_vl_bc($s_vl_bc)
    {
        $this->__load();
        return parent::setS_vl_bc($s_vl_bc);
    }

    public function getS_vl_iss()
    {
        $this->__load();
        return parent::getS_vl_iss();
    }

    public function setS_vl_iss($s_vl_iss)
    {
        $this->__load();
        return parent::setS_vl_iss($s_vl_iss);
    }

    public function getTipo_nota()
    {
        $this->__load();
        return parent::getTipo_nota();
    }

    public function setTipo_nota($iTipoNota)
    {
        $this->__load();
        return parent::setTipo_nota($iTipoNota);
    }

    public function getGrupo_nota()
    {
        $this->__load();
        return parent::getGrupo_nota();
    }

    public function setGrupo_nota($iGrupoNota)
    {
        $this->__load();
        return parent::setGrupo_nota($iGrupoNota);
    }

    public function getS_vl_pis()
    {
        $this->__load();
        return parent::getS_vl_pis();
    }

    public function setS_vl_pis($s_vl_pis)
    {
        $this->__load();
        return parent::setS_vl_pis($s_vl_pis);
    }

    public function getS_vl_cofins()
    {
        $this->__load();
        return parent::getS_vl_cofins();
    }

    public function setS_vl_cofins($s_vl_cofins)
    {
        $this->__load();
        return parent::setS_vl_cofins($s_vl_cofins);
    }

    public function getS_vl_inss()
    {
        $this->__load();
        return parent::getS_vl_inss();
    }

    public function setS_vl_inss($s_vl_inss)
    {
        $this->__load();
        return parent::setS_vl_inss($s_vl_inss);
    }

    public function getS_vl_ir()
    {
        $this->__load();
        return parent::getS_vl_ir();
    }

    public function setS_vl_ir($s_vl_ir)
    {
        $this->__load();
        return parent::setS_vl_ir($s_vl_ir);
    }

    public function getS_vl_csll()
    {
        $this->__load();
        return parent::getS_vl_csll();
    }

    public function setS_vl_csll($s_vl_csll)
    {
        $this->__load();
        return parent::setS_vl_csll($s_vl_csll);
    }

    public function getP_cnpjcpf()
    {
        $this->__load();
        return parent::getP_cnpjcpf();
    }

    public function setP_cnpjcpf($p_cnpjcpf)
    {
        $this->__load();
        return parent::setP_cnpjcpf($p_cnpjcpf);
    }

    public function getP_im()
    {
        $this->__load();
        return parent::getP_im();
    }

    public function setP_im($p_im)
    {
        $this->__load();
        return parent::setP_im($p_im);
    }

    public function getP_ie()
    {
        $this->__load();
        return parent::getP_ie();
    }

    public function setP_ie($p_ie)
    {
        $this->__load();
        return parent::setP_ie($p_ie);
    }

    public function getP_razao_social()
    {
        $this->__load();
        return parent::getP_razao_social();
    }

    public function setP_razao_social($p_razao_social)
    {
        $this->__load();
        return parent::setP_razao_social($p_razao_social);
    }

    public function getP_nome_fantasia()
    {
        $this->__load();
        return parent::getP_nome_fantasia();
    }

    public function setP_nome_fantasia($p_nome_fantasia)
    {
        $this->__load();
        return parent::setP_nome_fantasia($p_nome_fantasia);
    }

    public function getP_endereco()
    {
        $this->__load();
        return parent::getP_endereco();
    }

    public function setP_endereco($p_endereco)
    {
        $this->__load();
        return parent::setP_endereco($p_endereco);
    }

    public function getP_endereco_numero()
    {
        $this->__load();
        return parent::getP_endereco_numero();
    }

    public function setP_endereco_numero($p_endereco_numero)
    {
        $this->__load();
        return parent::setP_endereco_numero($p_endereco_numero);
    }

    public function getP_endereco_comp()
    {
        $this->__load();
        return parent::getP_endereco_comp();
    }

    public function setP_endereco_comp($p_endereco_comp)
    {
        $this->__load();
        return parent::setP_endereco_comp($p_endereco_comp);
    }

    public function getP_bairro()
    {
        $this->__load();
        return parent::getP_bairro();
    }

    public function setP_bairro($p_bairro)
    {
        $this->__load();
        return parent::setP_bairro($p_bairro);
    }

    public function getP_cod_municipio()
    {
        $this->__load();
        return parent::getP_cod_municipio();
    }

    public function setP_cod_municipio($p_cod_municipio)
    {
        $this->__load();
        return parent::setP_cod_municipio($p_cod_municipio);
    }

    public function getP_uf()
    {
        $this->__load();
        return parent::getP_uf();
    }

    public function setP_uf($p_uf)
    {
        $this->__load();
        return parent::setP_uf($p_uf);
    }

    public function getP_cod_pais()
    {
        $this->__load();
        return parent::getP_cod_pais();
    }

    public function setP_cod_pais($p_cod_pais)
    {
        $this->__load();
        return parent::setP_cod_pais($p_cod_pais);
    }

    public function getP_cep()
    {
        $this->__load();
        return parent::getP_cep();
    }

    public function setP_cep($p_cep)
    {
        $this->__load();
        return parent::setP_cep($p_cep);
    }

    public function getP_telefone()
    {
        $this->__load();
        return parent::getP_telefone();
    }

    public function setP_telefone($p_telefone)
    {
        $this->__load();
        return parent::setP_telefone($p_telefone);
    }

    public function getP_email()
    {
        $this->__load();
        return parent::getP_email();
    }

    public function setP_email($p_email)
    {
        $this->__load();
        return parent::setP_email($p_email);
    }

    public function getT_cnpjcpf()
    {
        $this->__load();
        return parent::getT_cnpjcpf();
    }

    public function setT_cnpjcpf($t_cnpjcpf)
    {
        $this->__load();
        return parent::setT_cnpjcpf($t_cnpjcpf);
    }

    public function getT_im()
    {
        $this->__load();
        return parent::getT_im();
    }

    public function setT_im($t_im)
    {
        $this->__load();
        return parent::setT_im($t_im);
    }

    public function getT_ie()
    {
        $this->__load();
        return parent::getT_ie();
    }

    public function setT_ie($t_ie)
    {
        $this->__load();
        return parent::setT_ie($t_ie);
    }

    public function getT_razao_social()
    {
        $this->__load();
        return parent::getT_razao_social();
    }

    public function setT_razao_social($t_razao_social)
    {
        $this->__load();
        return parent::setT_razao_social($t_razao_social);
    }

    public function getT_endereco()
    {
        $this->__load();
        return parent::getT_endereco();
    }

    public function setT_endereco($t_endereco)
    {
        $this->__load();
        return parent::setT_endereco($t_endereco);
    }

    public function getT_endereco_numero()
    {
        $this->__load();
        return parent::getT_endereco_numero();
    }

    public function setT_endereco_numero($t_endereco_numero)
    {
        $this->__load();
        return parent::setT_endereco_numero($t_endereco_numero);
    }

    public function getT_endereco_comp()
    {
        $this->__load();
        return parent::getT_endereco_comp();
    }

    public function setT_endereco_comp($t_endereco_comp)
    {
        $this->__load();
        return parent::setT_endereco_comp($t_endereco_comp);
    }

    public function getT_bairro()
    {
        $this->__load();
        return parent::getT_bairro();
    }

    public function setT_bairro($t_bairro)
    {
        $this->__load();
        return parent::setT_bairro($t_bairro);
    }

    public function getT_cod_municipio()
    {
        $this->__load();
        return parent::getT_cod_municipio();
    }

    public function setT_cod_municipio($t_cod_municipio)
    {
        $this->__load();
        return parent::setT_cod_municipio($t_cod_municipio);
    }

    public function getT_uf()
    {
        $this->__load();
        return parent::getT_uf();
    }

    public function setT_uf($t_uf)
    {
        $this->__load();
        return parent::setT_uf($t_uf);
    }

    public function getT_cod_pais()
    {
        $this->__load();
        return parent::getT_cod_pais();
    }

    public function setT_cod_pais($t_cod_pais)
    {
        $this->__load();
        return parent::setT_cod_pais($t_cod_pais);
    }

    public function getT_cep()
    {
        $this->__load();
        return parent::getT_cep();
    }

    public function setT_cep($t_cep)
    {
        $this->__load();
        return parent::setT_cep($t_cep);
    }

    public function getT_telefone()
    {
        $this->__load();
        return parent::getT_telefone();
    }

    public function setT_telefone($t_telefone)
    {
        $this->__load();
        return parent::setT_telefone($t_telefone);
    }

    public function getT_email()
    {
        $this->__load();
        return parent::getT_email();
    }

    public function setT_email($t_email)
    {
        $this->__load();
        return parent::setT_email($t_email);
    }

    public function getVl_liquido_nfse()
    {
        $this->__load();
        return parent::getVl_liquido_nfse();
    }

    public function setVl_liquido_nfse($vl_liquido_nfse)
    {
        $this->__load();
        return parent::setVl_liquido_nfse($vl_liquido_nfse);
    }

    public function getS_vl_outras_retencoes()
    {
        $this->__load();
        return parent::getS_vl_outras_retencoes();
    }

    public function setS_vl_outras_retencoes($s_vl_outras_retencoes)
    {
        $this->__load();
        return parent::setS_vl_outras_retencoes($s_vl_outras_retencoes);
    }

    public function getS_vl_aliquota()
    {
        $this->__load();
        return parent::getS_vl_aliquota();
    }

    public function setS_vl_aliquota($s_vl_aliquota)
    {
        $this->__load();
        return parent::setS_vl_aliquota($s_vl_aliquota);
    }

    public function getS_vl_desc_incondicionado()
    {
        $this->__load();
        return parent::getS_vl_desc_incondicionado();
    }

    public function setS_vl_desc_incondicionado($s_vl_desc_incondicionado)
    {
        $this->__load();
        return parent::setS_vl_desc_incondicionado($s_vl_desc_incondicionado);
    }

    public function getS_vl_condicionado()
    {
        $this->__load();
        return parent::getS_vl_condicionado();
    }

    public function setS_vl_condicionado($s_vl_condicionado)
    {
        $this->__load();
        return parent::setS_vl_condicionado($s_vl_condicionado);
    }

    public function getS_dados_iss_retido()
    {
        $this->__load();
        return parent::getS_dados_iss_retido();
    }

    public function setS_dados_iss_retido($s_dados_iss_retido)
    {
        $this->__load();
        return parent::setS_dados_iss_retido($s_dados_iss_retido);
    }

    public function getS_dados_resp_retencao()
    {
        $this->__load();
        return parent::getS_dados_resp_retencao();
    }

    public function setS_dados_resp_retencao($s_dados_resp_retencao)
    {
        $this->__load();
        return parent::setS_dados_resp_retencao($s_dados_resp_retencao);
    }

    public function getS_dados_item_lista_servico()
    {
        $this->__load();
        return parent::getS_dados_item_lista_servico();
    }

    public function setS_dados_item_lista_servico($s_dados_item_lista_servico)
    {
        $this->__load();
        return parent::setS_dados_item_lista_servico($s_dados_item_lista_servico);
    }

    public function getS_dados_cod_cnae()
    {
        $this->__load();
        return parent::getS_dados_cod_cnae();
    }

    public function setS_dados_cod_cnae($s_dados_cod_cnae)
    {
        $this->__load();
        return parent::setS_dados_cod_cnae($s_dados_cod_cnae);
    }

    public function getS_dados_cod_tributacao()
    {
        $this->__load();
        return parent::getS_dados_cod_tributacao();
    }

    public function setS_dados_cod_tributacao($s_dados_cod_tributacao)
    {
        $this->__load();
        return parent::setS_dados_cod_tributacao($s_dados_cod_tributacao);
    }

    public function getS_dados_cod_municipio()
    {
        $this->__load();
        return parent::getS_dados_cod_municipio();
    }

    public function setS_dados_cod_municipio($s_dados_cod_municipio)
    {
        $this->__load();
        return parent::setS_dados_cod_municipio($s_dados_cod_municipio);
    }

    public function getS_dados_cod_pais()
    {
        $this->__load();
        return parent::getS_dados_cod_pais();
    }

    public function setS_dados_cod_pais($s_dados_cod_pais)
    {
        $this->__load();
        return parent::setS_dados_cod_pais($s_dados_cod_pais);
    }

    public function getS_dados_exigibilidadeiss()
    {
        $this->__load();
        return parent::getS_dados_exigibilidadeiss();
    }

    public function setS_dados_exigibilidadeiss($s_dados_exigibilidadeiss)
    {
        $this->__load();
        return parent::setS_dados_exigibilidadeiss($s_dados_exigibilidadeiss);
    }

    public function getS_dados_municipio_incidencia()
    {
        $this->__load();
        return parent::getS_dados_municipio_incidencia();
    }

    public function setS_dados_municipio_incidencia($s_dados_municipio_incidencia)
    {
        $this->__load();
        return parent::setS_dados_municipio_incidencia($s_dados_municipio_incidencia);
    }

    public function getS_dados_num_processo()
    {
        $this->__load();
        return parent::getS_dados_num_processo();
    }

    public function setS_dados_num_processo($s_dados_num_processo)
    {
        $this->__load();
        return parent::setS_dados_num_processo($s_dados_num_processo);
    }

    public function getS_dec_cc_cod_obra()
    {
        $this->__load();
        return parent::getS_dec_cc_cod_obra();
    }

    public function setS_dec_cc_cod_obra($s_dec_cc_cod_obra)
    {
        $this->__load();
        return parent::setS_dec_cc_cod_obra($s_dec_cc_cod_obra);
    }

    public function getS_dec_cc_art()
    {
        $this->__load();
        return parent::getS_dec_cc_art();
    }

    public function setS_dec_cc_art($s_dec_cc_art)
    {
        $this->__load();
        return parent::setS_dec_cc_art($s_dec_cc_art);
    }

    public function getS_dec_reg_esp_tributacao()
    {
        $this->__load();
        return parent::getS_dec_reg_esp_tributacao();
    }

    public function setS_dec_reg_esp_tributacao($s_dec_reg_esp_tributacao)
    {
        $this->__load();
        return parent::setS_dec_reg_esp_tributacao($s_dec_reg_esp_tributacao);
    }

    public function getS_dec_incentivo_fiscal()
    {
        $this->__load();
        return parent::getS_dec_incentivo_fiscal();
    }

    public function setS_dec_incentivo_fiscal($s_dec_incentivo_fiscal)
    {
        $this->__load();
        return parent::setS_dec_incentivo_fiscal($s_dec_incentivo_fiscal);
    }

    public function getS_dec_simples_nacional()
    {
        $this->__load();
        return parent::getS_dec_simples_nacional();
    }

    public function setS_dec_simples_nacional($s_dec_simples_nacional)
    {
        $this->__load();
        return parent::setS_dec_simples_nacional($s_dec_simples_nacional);
    }

    public function getVl_credito()
    {
        $this->__load();
        return parent::getVl_credito();
    }

    public function setVl_credito($vl_credito)
    {
        $this->__load();
        return parent::setVl_credito($vl_credito);
    }

    public function getOutras_informacoes()
    {
        $this->__load();
        return parent::getOutras_informacoes();
    }

    public function setOutras_informacoes($outras_informacoes)
    {
        $this->__load();
        return parent::setOutras_informacoes($outras_informacoes);
    }

    public function getT_nome_fantasia()
    {
        $this->__load();
        return parent::getT_nome_fantasia();
    }

    public function setT_nome_fantasia($t_nome_fantasia)
    {
        $this->__load();
        return parent::setT_nome_fantasia($t_nome_fantasia);
    }

    public function getData_rps()
    {
        $this->__load();
        return parent::getData_rps();
    }

    public function setData_rps($data_rps)
    {
        $this->__load();
        return parent::setData_rps($data_rps);
    }

    public function getN_rps()
    {
        $this->__load();
        return parent::getN_rps();
    }

    public function setN_rps($n_rps)
    {
        $this->__load();
        return parent::setN_rps($n_rps);
    }

    public function getAno_comp()
    {
        $this->__load();
        return parent::getAno_comp();
    }

    public function setAno_comp($ano_comp)
    {
        $this->__load();
        return parent::setAno_comp($ano_comp);
    }

    public function getMes_comp()
    {
        $this->__load();
        return parent::getMes_comp();
    }

    public function setMes_comp($mes_comp)
    {
        $this->__load();
        return parent::setMes_comp($mes_comp);
    }

    public function getS_codigo_obra()
    {
        $this->__load();
        return parent::getS_codigo_obra();
    }

    public function setS_codigo_obra($s_codigo_obra)
    {
        $this->__load();
        return parent::setS_codigo_obra($s_codigo_obra);
    }

    public function getS_art()
    {
        $this->__load();
        return parent::getS_art();
    }

    public function setS_art($s_art)
    {
        $this->__load();
        return parent::setS_art($s_art);
    }

    public function getS_informacoes_complementares()
    {
        $this->__load();
        return parent::getS_informacoes_complementares();
    }

    public function setS_informacoes_complementares($s_informacoes_complementares)
    {
        $this->__load();
        return parent::setS_informacoes_complementares($s_informacoes_complementares);
    }

    public function getNatureza_operacao()
    {
        $this->__load();
        return parent::getNatureza_operacao();
    }

    public function setNatureza_operacao($iNaturezaOperacao)
    {
        $this->__load();
        return parent::setNatureza_operacao($iNaturezaOperacao);
    }

    public function getEmite_guia()
    {
        $this->__load();
        return parent::getEmite_guia();
    }

    public function setEmite_guia($lEmiteGuia)
    {
        $this->__load();
        return parent::setEmite_guia($lEmiteGuia);
    }

    public function getCancelada()
    {
        $this->__load();
        return parent::getCancelada();
    }

    public function setCancelada($lCancelada)
    {
        $this->__load();
        return parent::setCancelada($lCancelada);
    }

    public function getCancelamentoJustificativa()
    {
        $this->__load();
        return parent::getCancelamentoJustificativa();
    }

    public function setCancelamentoJustificativa($sCancelamentoJustificativa)
    {
        $this->__load();
        return parent::setCancelamentoJustificativa($sCancelamentoJustificativa);
    }

    public function setIdNotaSubstituida($id_nota_substituida)
    {
        $this->__load();
        return parent::setIdNotaSubstituida($id_nota_substituida);
    }

    public function getIdNotaSubstituida()
    {
        $this->__load();
        return parent::getIdNotaSubstituida();
    }

    public function setIdNotaSubstituta($id_nota_substituta)
    {
        $this->__load();
        return parent::setIdNotaSubstituta($id_nota_substituta);
    }

    public function getIdNotaSubstituta()
    {
        $this->__load();
        return parent::getIdNotaSubstituta();
    }

    public function getId_contribuinte()
    {
        $this->__load();
        return parent::getId_contribuinte();
    }

    public function setId_contribuinte($iIdContribuinte)
    {
        $this->__load();
        return parent::setId_contribuinte($iIdContribuinte);
    }

    public function getId_usuario()
    {
        $this->__load();
        return parent::getId_usuario();
    }

    public function setId_usuario($iIdUsuario)
    {
        $this->__load();
        return parent::setId_usuario($iIdUsuario);
    }

    public function getImportada()
    {
        $this->__load();
        return parent::getImportada();
    }

    public function setImportada($lImportada)
    {
        $this->__load();
        return parent::setImportada($lImportada);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nota', 'dt_nota', 'hr_nota', 'cod_verificacao', 's_dados_discriminacao', 's_vl_servicos', 's_vl_deducoes', 's_vl_bc', 's_vl_iss', 'tipo_nota', 'grupo_nota', 'ano_comp', 'mes_comp', 's_vl_pis', 's_vl_cofins', 's_vl_inss', 's_vl_ir', 's_vl_csll', 'p_cnpjcpf', 'p_im', 'p_ie', 'p_razao_social', 'p_nome_fantasia', 'p_endereco', 'p_endereco_numero', 'p_endereco_comp', 'p_bairro', 'p_cod_municipio', 'p_uf', 'p_cod_pais', 'p_cep', 'p_telefone', 'p_email', 't_cnpjcpf', 't_im', 't_ie', 't_razao_social', 't_nome_fantasia', 't_endereco', 't_endereco_numero', 't_endereco_comp', 't_bairro', 't_cod_municipio', 't_uf', 't_cod_pais', 't_cep', 't_telefone', 't_email', 'vl_liquido_nfse', 's_vl_outras_retencoes', 's_vl_aliquota', 's_vl_desc_incondicionado', 's_vl_condicionado', 's_dados_iss_retido', 's_dados_resp_retencao', 's_dados_item_lista_servico', 's_dados_cod_cnae', 's_dados_cod_tributacao', 's_dados_cod_municipio', 's_dados_cod_pais', 's_dados_exigibilidadeiss', 's_dados_municipio_incidencia', 's_dados_num_processo', 's_dec_cc_cod_obra', 's_dec_cc_art', 's_dec_reg_esp_tributacao', 's_dec_incentivo_fiscal', 's_dec_simples_nacional', 'vl_credito', 'outras_informacoes', 'data_rps', 'n_rps', 's_codigo_obra', 's_art', 's_informacoes_complementares', 'natureza_operacao', 'emite_guia', 'cancelada', 'cancelamento_justificativa', 'id_nota_substituida', 'id_nota_substituta', 'id_contribuinte', 'id_usuario', 'importada', 'guia');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}