<?php

namespace Proxy\__CG__\Administrativo;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Controle extends \Administrativo\Controle implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getNome()
    {
        $this->__load();
        return parent::getNome();
    }

    public function setNome($controle)
    {
        $this->__load();
        return parent::setNome($controle);
    }

    public function getModulo()
    {
        $this->__load();
        return parent::getModulo();
    }

    public function setModulo($modulo)
    {
        $this->__load();
        return parent::setModulo($modulo);
    }

    public function getIdentidade()
    {
        $this->__load();
        return parent::getIdentidade();
    }

    public function setIdentidade($sIdentidade)
    {
        $this->__load();
        return parent::setIdentidade($sIdentidade);
    }

    public function getVisivel()
    {
        $this->__load();
        return parent::getVisivel();
    }

    public function setVisivel($lVisivel)
    {
        $this->__load();
        return parent::setVisivel($lVisivel);
    }

    public function getAcoes()
    {
        $this->__load();
        return parent::getAcoes();
    }

    public function addAcao(\Administrativo\Acao $acao)
    {
        $this->__load();
        return parent::addAcao($acao);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'controle', 'identidade', 'visivel', 'modulo', 'acoes');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}