<?php foreach ($this->aDadosNota as $iPagina => $oDadosPagina) {
if ($oDadosPagina->iPagina == 1) {?>  
  
	<?php if (!$this->lHtmlEmbutido) { ?>
	  <!DOCTYPE html>
    <html xmlns="http://www.w3.org/1999/xhtml">
	  <head>
	<?php } ?>
  
    <style type="text/css">
    
      <?php if (!$this->lHtmlEmbutido) { ?>
      
        body {
          width: 1200px;
          margin: 0;
          font-size: 11px;
          font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        }
      <?php } ?>
    table {
      text-align: center;
      border-collapse: collapse;
      width: 100%;
    }

    table tr td {
      text-align: left;
      padding-left: 5px;
    }

    table tr td.center {
      text-align: center;
    }

    table tr td.titulo {
      padding: 5px;
      font-weight: bold;
    }

    table tr td.imagem {
      width: 120px;
      height: 120px;
    }

    table tr td.linha {
      line-height: 2px;
      background-color: black;
    }

    .nfse_cancelada {
      position: absolute;
      width: 100%;
    }

    .nfse_cancelada_img {
      margin: 30% 10% 0;
    }

    .underline {
      text-decoration: underline;
    }
  </style>
  <?php if (!$this->lHtmlEmbutido) { ?>
    </head>
    <body style="margin: auto">
  <?php }?>
<?php }?>
  <div class="nfse_cancelada">
    <?php if (is_file(PUBLIC_PATH . $oDadosPagina->oDadosCabecalho->sUrlTarja)) { ?>
      <img class="nfse_cancelada_img" src="<?php echo $oDadosPagina->oDadosCabecalho->sUrlTarja ?>">
    <?php } ?>
  </div>

  <table>
    <tr>
      <td colspan="2" class="imagem">
        <?php if (is_file(PUBLIC_PATH . $oDadosPagina->oDadosCabecalho->sBrasao)) { ?>
          <img src="<?php echo $oDadosPagina->oDadosCabecalho->sBrasao ?>" width="100px" height="100px">
        <?php } ?>
      </td>
      <td>
        <?php echo $oDadosPagina->oDadosCabecalho->oDadosPrefeitura->getNome() ?>
        <br>
        <?php echo $oDadosPagina->oDadosCabecalho->oDadosPrefeitura->getSecretaria() ?>
        <br>
        <span class="underline"><?php echo $oDadosPagina->oDadosCabecalho->oDadosPrefeitura->getSetor() ?></span>
        <br>
          <span class="underline"><?php echo $oDadosPagina->oDadosCabecalho->oDadosPrefeitura->getEndereco() . ', ' .
              $oDadosPagina->oDadosCabecalho->oDadosPrefeitura->getNumero() . ' - ' .
              $oDadosPagina->oDadosCabecalho->oDadosPrefeitura->getBairro() . ' / ' .
              $oDadosPagina->oDadosCabecalho->oDadosPrefeitura->getMunicipio() . ' - ' .
              $oDadosPagina->oDadosCabecalho->oDadosPrefeitura->getUf() . ' / CEP: ' .
              $oDadosPagina->oDadosCabecalho->oDadosPrefeitura->getCep(); ?>
          </span>
      </td>
      <td rowspan="8" class="center" style="border: #000000 solid 1px;">
        <table>
          <tr>
            <td class="center titulo">Número Nota</td>
          </tr>
          <tr>
            <td class="center titulo"><?php echo $oDadosPagina->oDadosServico->oDadosNota->getNota() ?></td>
          </tr>
          <tr>
            <td class="center titulo">Folha <?php echo $iPagina + 1 . '/' . count($this->aDadosNota)?></td>
          </tr>
          <tr>
            <td class="center titulo">Código Verificação</td>
          </tr>
          <tr>
            <td class="center titulo"><?php echo $oDadosPagina->oDadosServico->oDadosNota->getCod_verificacao() ?></td>
          </tr>
          <tr>
            <?php if (is_file(PUBLIC_PATH . $oDadosPagina->oDadosCabecalho->sQRCode)) { ?>
              <td class="center"><img src="<?php echo $oDadosPagina->oDadosCabecalho->sQRCode ?>"></td>
            <?php } ?>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td colspan="3" class="linha"></td>
    </tr>
    <tr>
      <td colspan="3">
        <table style="height: 125px;">
          <tr>
            <td colspan="3" class="titulo center">Nota Fiscal de Serviços Eletrônica - NFSe</td>
          </tr>
          <tr>
            <td width="20%">Emissão (Horário de Brasília)</td>
            <td class="center" width="20%">Período de Competência</td>
            <td width="30%">Município de Prestaçao do Serviço</td>
          </tr>
          <tr>
            <td>
              <b><?php echo $oDadosPagina->oDadosServico->oDadosNota->formatedData() . ' - ' . 
              $oDadosPagina->oDadosServico->oDadosNota->formatedHora() ?></b>
            </td>
            <td class="center"><b><?php echo str_pad($oDadosPagina->oDadosServico->oDadosNota->getComp(), 7, 0, STR_PAD_LEFT) ?></b></td>
            <td><b><?php echo $oDadosPagina->oDadosServico->oDadosNota->getServicoMunicipio() ?></b></td>
          </tr>
          <tr>
            <td>Reg. Especial Tributação</td>
            <td class="center"><?php echo isset($oDadosPagina->oDadosServico->oDadosNotaSubstituida) ?
                'Número Nota Substituida' : NULL ?></td>
            <td>Natureza da Operação</td>
          </tr>
          <tr>
            <td><b><?php echo $oDadosPagina->oDadosPrestador->oPrestador->getDescricaoRegimeTributario() ?></b></td>
            <td class="center">
              <?php echo isset($oDadosPagina->oDadosServico->oDadosNotaSubstituida) 
                ? "<b>{$oDadosPagina->oDadosServico->oDadosNotaSubstituida->getNota()}</b>" : NULL ?>
            </td>
            <td>
              <b>
                <?php echo Contribuinte_Model_NaturezaOperacao::getById(
                    $oDadosPagina->oDadosServico->oDadosNota->getNatureza_operacao()) ?>
              </b>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td colspan="3">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="3" class="linha"></td>
    </tr>
  </table>
  <br>
  <table>
    <tr>
      <td colspan="5">PRESTADOR DE SERVIÇOS</td>
    </tr>
    <tr>
      <td rowspan="6" class="center imagem">
        <?php if (is_file(PUBLIC_PATH . $oDadosPagina->oDadosPrestador->sLogoPrestador)) { ?>
          <img alt="" width="100px" height="100px" src="<?php echo $oDadosPagina->oDadosPrestador->sLogoPrestador ?>">
        <?php } ?>
      </td>
      <td colspan="3">Razão Social</td>
      <td>CPF/CNPJ</td>
    </tr>
    <tr>
      <td colspan="3"><b><?php echo $oDadosPagina->oDadosServico->oDadosNota->getP_razao_social() ?></b></td>
      <td><b><?php echo DBSeller_Helper_Number_Format::maskCPF_CNPJ($oDadosPagina->oDadosServico->oDadosNota->getP_cnpjcpf()) ?></b></td>
    </tr>
    <tr>
      <td width="25%">Inscrição Municipal</td>
      <td>Fone/Fax</td>
      <td>Simples Nacional</td>
      <td>Incentivador Cultural</td>
    </tr>
    <tr>
      <td width="80px"><b><?php echo $oDadosPagina->oDadosServico->oDadosNota->getP_im() ?></b></td>
      <td><?php echo DBSeller_Helper_Number_Format::maskPhoneNumber($oDadosPagina->oDadosServico->oDadosNota->getP_telefone()) ?></td>
      <td><?php echo $oDadosPagina->oDadosPrestador->oPrestador->getDescricaoOptanteSimples() ?></td>
      <td>Não</td>
    </tr>
    <tr>
      <td colspan="4">Endereço</td>
    </tr>
    <tr>
      <td colspan="2"><?php echo $oDadosPagina->oDadosServico->oDadosNota->getP_endereco() . ', ' .
          $oDadosPagina->oDadosServico->oDadosNota->getP_endereco_numero() . ' ' .
          $oDadosPagina->oDadosServico->oDadosNota->getP_endereco_comp() ?>
      </td>
      <td>CEP: <?php echo $oDadosPagina->oDadosServico->oDadosNota->getP_cep() ?></td>
      <td><?php echo $oDadosPagina->oDadosServico->oDadosNota->getPrestadorMunicipio() . ' / ' . 
          $oDadosPagina->oDadosServico->oDadosNota->getP_uf() ?>
      </td>
    </tr>
    <tr>
      <td colspan="5" class="linha"></td>
    </tr>
  </table>
  <br>
<?php if ($oDadosPagina->iPagina == 1) {?>  
  <table>
    <tr>
      <td colspan="3">TOMADOR DE SERVIÇOS</td>
    </tr>
    <tr>
      <td colspan="2" width="200px">Razão Social</td>
      <td>CPF/CNPJ</td>
    </tr>
    <tr>
      <td colspan="2">
        <?php if ($oDadosPagina->oDadosServico->oDadosNota->getT_razao_social()) { ?>
          <b><?php echo $oDadosPagina->oDadosServico->oDadosNota->getT_razao_social() ?></b>
        <?php } else { ?>
          Não identificado
        <?php } ?>
      </td>
      <td><b><?php echo DBSeller_Helper_Number_Format::maskCPF_CNPJ($oDadosPagina->oDadosServico->oDadosNota->getT_cnpjcpf()) ?></b></td>
    </tr>
    <tr>
      <td width="25%">Inscrição Municipal</td>
      <td>Fone/Fax</td>
      <td>Email</td>
    </tr>
    <tr>
      <td><b><?php echo $oDadosPagina->oDadosServico->oDadosNota->getT_im() ?></b></td>
      <td><?php echo DBSeller_Helper_Number_Format::maskPhoneNumber($oDadosPagina->oDadosServico->oDadosNota->getT_telefone()) ?></td>
      <td><?php echo $oDadosPagina->oDadosServico->oDadosNota->getT_email() ?></td>
    </tr>
    <tr>
      <td colspan="3">Endereço</td>
    </tr>
    <tr>
      <td colspan="3">
        <?php if ($oDadosPagina->oDadosServico->oDadosNota->getT_cnpjcpf()) { ?>
          <?php echo $oDadosPagina->oDadosServico->oDadosNota->getT_endereco() . ', ' .
            $oDadosPagina->oDadosServico->oDadosNota->getT_endereco_numero() . ' ' .
            $oDadosPagina->oDadosServico->oDadosNota->getT_endereco_comp() . ' ' .
            $oDadosPagina->oDadosServico->oDadosNota->getT_cep() . ' - ' .
            $oDadosPagina->oDadosServico->oDadosNota->getTomadorMunicipio() . ' / ' .
            $oDadosPagina->oDadosServico->oDadosNota->getT_uf();
          ?>
        <?php } ?>
      </td>
    </tr>
    <tr>
      <td colspan="3" class="linha"></td>
    </tr>
  </table>
  <br>
  <?php }?>
  <table>
    <?php if ($oDadosPagina->iPagina == 1) {?>  
    <tr>
      <td>
        Código Tributação Município:
        <?php
        echo "{$oDadosPagina->oDadosServico->oDadosNota->getS_dados_item_lista_servico()} -
         {$oDadosPagina->oDadosServico->oDadosNota->getDescricaoListaServico()}";
        ?>
      </td>
    </tr>
    <tr>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>
        CNAE:
        <?php echo "{$oDadosPagina->oDadosServico->oDadosNota->getS_dados_cod_cnae()}"; ?> -
        <?php
        $aServico = Contribuinte_Model_Servico::getByCodServico(
          $oDadosPagina->oDadosServico->oDadosNota->getS_dados_cod_tributacao()
        );
        $oServico = reset($aServico);
        echo ($oServico instanceof Contribuinte_Model_Servico) ? $oServico->attr('desc_cnae') : NULL;
        ?>
      </td>
    </tr>
    <?php }?>
    <tr>
      <td class="linha"></td>
    </tr>
    <tr>
      <td class="center destacado titulo"> DISCRIMINAÇÃO DOS SERVIÇOS</td>
    </tr>
    <tr>
      <td height="130px" style="vertical-align: top">
        <?php echo $oDadosPagina->oDadosServico->sDiscriminacaoServico ?>
      </td>
    </tr>
    <tr>
      <td class="linha"></td>
    </tr>
  </table>
  <br>
  <?php if ($oDadosPagina->iPagina == 1) {?>  
  <table>
    <tr>
      <td colspan="6">RETENÇÕES FEDERAIS</td>
    </tr>
    <tr>
      <td>PIS (R$)</td>
      <td>COFINS(R$)</td>
      <td>INSS (R$)</td>
      <td>IR (R$)</td>
      <td>CSLL (R$)</td>
      <td>Outras Retenções (R$)</td>
    </tr>
    <tr>
      <td><?php echo number_format($oDadosPagina->oDadosServico->oDadosNota->getS_vl_pis(), 2, ',', '.') ?></td>
      <td><?php echo number_format($oDadosPagina->oDadosServico->oDadosNota->getS_vl_cofins(), 2, ',', '.') ?></td>
      <td><?php echo number_format($oDadosPagina->oDadosServico->oDadosNota->getS_vl_inss(), 2, ',', '.') ?></td>
      <td><?php echo number_format($oDadosPagina->oDadosServico->oDadosNota->getS_vl_ir(), 2, ',', '.') ?></td>
      <td><?php echo number_format($oDadosPagina->oDadosServico->oDadosNota->getS_vl_csll(), 2, ',', '.') ?></td>
      <td><?php echo number_format($oDadosPagina->oDadosServico->oDadosNota->getS_vl_outras_retencoes(), 2, ',', '.') ?></td>
    </tr>
    <tr>
      <td colspan="6" class="linha"></td>
    </tr>
  </table>
  <br>
  <table>
    <tr>
      <td colspan="5">VALORES</td>
    </tr>
    <tr>
      <td>Valor dos Serviços</td>
      <td>Deduções</td>
      <td>Desconto Incondicionado</td>
      <td>Base de Cálculo</td>
      <td>Alíquota %</td>
    </tr>
    <tr>
      <td><?php echo number_format($oDadosPagina->oDadosServico->oDadosNota->getS_vl_servicos(), 2, ',', '.') ?></td>
      <td><?php echo number_format($oDadosPagina->oDadosServico->oDadosNota->getS_vl_deducoes(), 2, ',', '.') ?></td>
      <td><?php echo number_format($oDadosPagina->oDadosServico->oDadosNota->getS_vl_desc_incondicionado(), 2, ',', '.') ?></td>
      <td><?php echo number_format($oDadosPagina->oDadosServico->oDadosNota->getS_vl_bc(), 2, ',', '.') ?></td>
      <td><?php echo number_format($oDadosPagina->oDadosServico->oDadosNota->getS_vl_aliquota(), 2, ',', '.') ?></td>
    </tr>
    <tr>
      <td>ISS Prestador (R$)</td>
      <td>ISS Tomador (R$)</td>
      <td>Desconto Condicionado</td>
      <td>Valor Total da Nota (R$)</td>
      <td>Valor Liquido (R$)</td>
    </tr>
    <tr>
      <?php if ($oDadosPagina->oDadosServico->oDadosNota->getS_dados_iss_retido() == Contribuinte_Model_Nota::PRESTADOR_RETEM_ISS &&
        !$oDadosPagina->oDadosServico->oDadosNota->getEmite_guia()
      ) {
        ?>
        <td><?php echo number_format(0, 2, ',', '.') ?></td>
        <td><?php echo number_format(0, 2, ',', '.') ?></td>
      <?php } else if ($oDadosPagina->oDadosServico->oDadosNota->getS_dados_iss_retido() == Contribuinte_Model_Nota::TOMADOR_RETEM_ISS) { ?>
        <td><?php echo number_format(0, 2, ',', '.') ?></td>
        <td><?php echo number_format($oDadosPagina->oDadosServico->oDadosNota->getS_vl_iss(), 2, ',', '.') ?></td>
      <?php } else { ?>
        <td><?php echo number_format($oDadosPagina->oDadosServico->oDadosNota->getS_vl_iss(), 2, ',', '.') ?></td>
        <td><?php echo number_format(0, 2, ',', '.') ?></td>
      <?php } ?>
      <td><?php echo number_format($oDadosPagina->oDadosServico->oDadosNota->getS_vl_condicionado(), 2, ',', '.') ?></td>
      <td><?php echo number_format($oDadosPagina->oDadosServico->oDadosNota->getS_vl_servicos(), 2, ',', '.') ?></td>
      <td><?php echo number_format($oDadosPagina->oDadosServico->oDadosNota->getVl_liquido_nfse(), 2, ',', '.') ?></td>
    </tr>
    <tr>
      <td colspan="5" class="linha"></td>
    </tr>
  </table>
  <br>
  <?php  if ($oDadosPagina->oDadosCabecalho->oDadosPrefeitura->getInformacoesComplementaresNfse() ||
    $oDadosPagina->oDadosServico->oDadosNota->getS_informacoes_complementares()
  ) {
  ?>
  <table>
    <tr>
      <td class="titulo">OUTRAS INFORMAÇÕES</td>
    </tr>
    <tr>
      <td>
        <?php echo $oDadosPagina->oDadosCabecalho->oDadosPrefeitura->getInformacoesComplementaresNfse() ?>
        <br>
        <?php echo $oDadosPagina->oDadosServico->oDadosNota->getS_informacoes_complementares() ?>
      </td>
    </tr>
    <tr>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td class="linha"></td>
    </tr>
  </table>
  <?php } ?>
<?php } ?>
  <br />
  <?php if (count($this->aDadosNota) == $oDadosPagina->iPagina && !$this->lHtmlEmbutido) {?>
  	</body>
    </html>
  <?php }?>
<?php } ?>